server:
  port: 8082

spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessactivity
      database: fitnessactivity

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
