
server:
  port: 8083

spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb://localhost:27018/fitnessrecomendation
      database: fitnessrecommendation

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/