# configserver/src/main/resources/application.yml
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
          # THIS IS THE NEW, CRUCIAL SETTING
          skip-override: false # Default is true. Set to false to process placeholders.
        override-none: true
        overrides:
          GEMINI_API_URL: ${GEMINI_API_URL:https://default-fallback-url.com}
          GEMINI_API_KEY: ${GEMINI_API_KEY:default-key}

server:
  port: 8888