version: '3.9'
services:
  mongodb:
    image: mongo:6.0
    container_name: fitness-mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: fitnessactivity
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
